# Generated by Django 4.2.5 on 2023-09-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_rename_card_id_cart_cart_id"),
    ]

    operations = [
        migrations.AlterModelTable(name="cart", table="Cart",),
    ]
